name: ci

on:
  push:
    paths-ignore:
      - "docs/**"

jobs:
  test:
    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Set up python
        run: uv python install
      - name: Run linter
        run: uv run ruff check
      - name: Run unit tests
        run: uv run -m unittest
