name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: generate docs with pdoc3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - run: pip install pdoc3
      - run: python setup.py develop
      - run: pdoc --html dphon
      - run: rm -rf docs/* && mv html/dphon/* docs/
      - uses: EndBug/add-and-commit@v5
        with:
          add: "docs/ --force"
          message: "Update documentation"
