name: release

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  publish:
    name: publish to pyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Set up python
        run: uv python install
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish
