name: release

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  publish:
    name: publish to pyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Set up python
        run: uv python install
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish
