name: release

on:
  release:
    types: [published]

jobs:
  publish:
    name: publish to pyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
      - run: pip install -r dev-requirements.txt
      - run: python -m build
      - run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
